# Generated by Django 4.2.5 on 2023-10-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0002_institution_alter_bags_options_alter_bags_name_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bags',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bags.institution', verbose_name='Institucion'),
        ),
        migrations.AlterField(
            model_name='bags',
            name='products_not_received',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bags.not_received', verbose_name='Productos No Devueltos'),
        ),
        migrations.AlterField(
            model_name='bags',
            name='products_received',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bags.received', verbose_name='Productos Recibidos'),
        ),
    ]
