# Generated by Django 4.2.5 on 2023-10-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_code_alter_product_cost_and_more'),
        ('bags', '0003_alter_bags_institution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationProductSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bags.sent')),
            ],
        ),
        migrations.RemoveField(
            model_name='sent',
            name='products',
        ),
        migrations.AddField(
            model_name='sent',
            name='products',
            field=models.ManyToManyField(through='bags.RelationProductSent', to='products.product', verbose_name='productos enviados'),
        ),
    ]
