# Generated by Django 4.2.5 on 2023-10-17 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_code_alter_product_cost_and_more'),
        ('bags', '0006_alter_productsent_options_productreceived_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Not_received',
            new_name='NotReceived',
        ),
        migrations.CreateModel(
            name='ProductNotReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('not_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bags.notreceived')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Producto no recibido',
                'verbose_name_plural': 'Productos no recibidos',
            },
        ),
    ]
