# Generated by Django 4.2.5 on 2023-10-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_code_alter_product_cost_and_more'),
        ('bags', '0007_rename_not_received_notreceived_productnotreceived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productnotreceived',
            options={'verbose_name': 'Producto no devuelto', 'verbose_name_plural': 'Productos no devueltos'},
        ),
        migrations.RemoveField(
            model_name='notreceived',
            name='products',
        ),
        migrations.AddField(
            model_name='notreceived',
            name='products',
            field=models.ManyToManyField(through='bags.ProductNotReceived', to='products.product', verbose_name='productos no recibidos'),
        ),
    ]
