# Generated by Django 4.2.5 on 2023-10-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='armhole',
            field=models.CharField(choices=[('Chica', 'Chica'), ('Normal', 'Normal'), ('Grande', 'Grande')], max_length=6, verbose_name='Moldería'),
        ),
    ]
