# Generated by Django 4.2.5 on 2023-11-01 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_code_alter_product_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryproduct',
            old_name='description',
            new_name='name',
        ),
    ]
